### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Xiphoseer** [LUDevNet/LUpdate#1]
- [ ] incremental PK file writing (how to do reset?)
- [ ] support no PKI file
- [ ] generate versions.txt and frontend.txt
- [ ] ...?
